 # This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run build
          - pipe: atlassian/aws-elasticbeanstalk-deploy:0.6.2
            variables:
               APPLICATION_NAME: 'Kitabeli-Dashboard-Dev'
               ENVIRONMENT_NAME: 'KitabeliDashboardDev-env'
               ZIP_FILE: 'application.zip' 
               S3_BUCKET: 'elasticbeanstalk-us-east-2-591076044691'
               AWS_DEFAULT_REGION:  'us-east-2'
               